language: python
python:
- '3.6'
install:
- find -name '*requirements.txt' -exec pip install -r {} \;
script: make -f ./build-scripts/project.mk publish
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_94aabc157ce6_key -iv $encrypted_94aabc157ce6_iv
  -in travis/deploy_key.enc -out ~/deploy_key -d
- openssl aes-256-cbc -K $encrypted_9cb6e1718829_key -iv $encrypted_9cb6e1718829_iv
  -in travis/pypirc.enc -out ~/.pypirc -d
- chmod 600 ${DIR}/deploy_key
- eval $(ssh-agent -s)
- ssh-add ${DIR}/deploy_key
