language: python
python:
  - '3.6'
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_94aabc157ce6_key -iv $encrypted_94aabc157ce6_iv
    -in travis/deploy_key.enc -out ~/deploy_key -d
  - chmod 600 ~/deploy_key
  - eval $(ssh-agent -s)
  - ssh-add ~/deploy_key
install:
  - pip install twine
script:
  - make
  - twine upload dist/*
branches:
  only:
  - master

