language: python
python:
- '3.6'
install:
- pip install -r build-requirements.txt
script: make -f ./build-scripts/project.mk publish
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_94aabc157ce6_key -iv $encrypted_94aabc157ce6_iv
  -in travis/deploy_key.enc -out build-scripts/deploy_key -d
- openssl aes-256-cbc -K $encrypted_9cb6e1718829_key -iv $encrypted_9cb6e1718829_iv
  -in travis/pypirc.enc -out build-scripts/pypirc -d
