language: python
python:
- '2.7'
install:
- pip install -r build-requirements.txt
script: make publish
sudo: false
branches:
  only:
  - python2
before_install:
- openssl aes-256-cbc -K $encrypted_94aabc157ce6_key -iv $encrypted_94aabc157ce6_iv
  -in build-scripts/deploy_key.enc -out build-scripts/deploy_key -d
- openssl aes-256-cbc -K $encrypted_9cb6e1718829_key -iv $encrypted_9cb6e1718829_iv
  -in build-scripts/pypirc.enc -out build-scripts/pypirc -d
